def e(f, i):
    try:
        return f()
    except [insert]:
        traceback.print_exc()
        input(f'Error on {i}...')
